### ISSUE TITLE
Texas Testing Laptop Still Trying to Resume Previous FR1 session instead of incrementing

### ISSUE THREAD

**Issue by dunadan67** [ramdarpaprojectorg/RAMControl#19]
Thought this had been addressed?

**Comment by mivade** [comment]
Please provide more information. 

Have you checked out the correct branch? Try `git show HEAD` to see the commit hash.

Are you running in debug mode?

How are you running things? Are you reaching the end to quit or breaking early?

**Comment by mivade** [comment]
It advances for me as long as it is run to completion and you press a button after the "thanks for playing" message at the end.

**Comment by dunadan67** [comment]
First thing I did was check what branch was being used.  It was correct.  We were not running in debug mode.

I'll check with Alexis about the button push.  She told me she ran a full session.

**Comment by dunadan67** [comment]
Alexis tells me she pressed STOP in RAMulator when the session ended, instead of clicking through on the testing laptop.  I'll be sure to emphasize this during training.  Closing this.
