### ISSUE TITLE
FR practice list is always presented in alphabetical order

### ISSUE THREAD

**Issue by dunadan67** [ramdarpaprojectorg/RAMControl#22]
Not a big deal but it used to be randomized in previous systems.

**Comment by mivade** [comment]
It has always been in the same order in System 3.

**Comment by dunadan67** [comment]
Right.  I just noticed it.  I think in System 2 and System 1 it was
randomized.  Not sure if it matters.

**Comment by mivade** [comment]
Youssef says it would probably better to randomize the words. I'll make this change but delay rolling it out until the next batch of updates.

**Comment by mivade** [comment]
Implemented in cbe57b2.
